Repository hacf-fr/renault-api, pull requests merged in 2020-11, with the labels that each got.

#12 Align Python versions used in CI with HA core
  .github/workflows/tests.yml
  CONTRIBUTING.rst
  noxfile.py
  poetry.lock
  pyproject.toml
Labels: CI

#28 Update tests for api keys
  tests/conftest.py
  tests/test_api_keys.py
Labels: CI

#31 Add gigya sample responses
  tests/fixtures/gigya/account_info.txt
  tests/fixtures/gigya/account_info_corrupted.txt
  tests/fixtures/gigya/get_jwt.txt
  tests/fixtures/gigya/get_jwt_corrupted.txt
  tests/fixtures/gigya/login.txt
  tests/fixtures/gigya/login_failed.txt
Labels: CI

#30 Add Kamereon sample responses
  tests/fixtures/kamereon/account_vehicles.txt
  tests/fixtures/kamereon/errors/invalid_upstream.txt
  tests/fixtures/kamereon/errors/not_supported.txt
  tests/fixtures/kamereon/errors/quota_limit.txt
  tests/fixtures/kamereon/persons_detail.txt
  tests/fixtures/kamereon/vehicle/battery-status.1.txt
  tests/fixtures/kamereon/vehicle/battery-status.2.txt
  tests/fixtures/kamereon/vehicle/charge-history.txt
  tests/fixtures/kamereon/vehicle/charges.txt
  tests/fixtures/kamereon/vehicle/cockpit.txt
  tests/fixtures/kamereon/vehicle/hvac-status.txt
  tests/fixtures/kamereon/vehicle_actions/charge-mode.schedule_mode.txt
  tests/fixtures/kamereon/vehicle_actions/charge-schedule.schedules.txt
  tests/fixtures/kamereon/vehicle_actions/charging-start.start.txt
  tests/fixtures/kamereon/vehicle_actions/hvac-start.cancel.txt
  tests/fixtures/kamereon/vehicle_actions/hvac-start.start.invalid_date.txt
  tests/fixtures/kamereon/vehicle_actions/hvac-start.start.txt
Labels: CI

#34 Add models for Gigya
  poetry.lock
  pyproject.toml
  src/renault_api/exceptions.py
  src/renault_api/model/__init__.py
  src/renault_api/model/gigya.py
  tests/fixtures/gigya/account_info.json
  tests/fixtures/gigya/account_info.txt
  tests/fixtures/gigya/account_info_corrupted.txt
  tests/fixtures/gigya/get_jwt.json
  tests/fixtures/gigya/get_jwt.txt
  tests/fixtures/gigya/get_jwt_corrupted.txt
  tests/fixtures/gigya/login.json
  tests/fixtures/gigya/login.txt
  tests/fixtures/gigya/login_failed.json
  tests/fixtures/gigya/login_failed.txt
  tests/model/test_gigya.py
Labels: enhancement

#39 Add pytest-cov to dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies

#29 Pin aiohttp to 3.7.1 to match HA
  poetry.lock
  pyproject.toml
Labels: dependencies

#37 Add models for Kamereon
  src/renault_api/exceptions.py
  src/renault_api/model/__init__.py
  src/renault_api/model/kamereon.py
  tests/fixtures/kamereon/account_vehicles.txt
  tests/fixtures/kamereon/errors/invalid_upstream.txt
  tests/fixtures/kamereon/errors/not_supported.txt
  tests/fixtures/kamereon/errors/quota_limit.txt
  tests/fixtures/kamereon/person.json
  tests/fixtures/kamereon/persons_detail.txt
  tests/fixtures/kamereon/vehicle/battery-status.1.txt
  tests/fixtures/kamereon/vehicle/battery-status.2.txt
  tests/fixtures/kamereon/vehicle/charge-history.txt
  tests/fixtures/kamereon/vehicle/charges.txt
  tests/fixtures/kamereon/vehicle/cockpit.txt
  tests/fixtures/kamereon/vehicle/hvac-status.txt
  tests/fixtures/kamereon/vehicle_action/charge-mode.schedule_mode.json
  tests/fixtures/kamereon/vehicle_action/charge-schedule.schedules.json
  tests/fixtures/kamereon/vehicle_action/charging-start.start.json
  tests/fixtures/kamereon/vehicle_action/hvac-start.cancel.json
  tests/fixtures/kamereon/vehicle_action/hvac-start.start.json
  tests/fixtures/kamereon/vehicle_actions/charge-mode.schedule_mode.txt
  tests/fixtures/kamereon/vehicle_actions/charge-schedule.schedules.txt
  tests/fixtures/kamereon/vehicle_actions/charging-start.start.txt
  tests/fixtures/kamereon/vehicle_actions/hvac-start.cancel.txt
  tests/fixtures/kamereon/vehicle_actions/hvac-start.start.invalid_date.txt
  tests/fixtures/kamereon/vehicle_actions/hvac-start.start.txt
  tests/fixtures/kamereon/vehicle_data/battery-status.1.json
  tests/fixtures/kamereon/vehicle_data/battery-status.2.json
  tests/fixtures/kamereon/vehicle_data/charge-history.json
  tests/fixtures/kamereon/vehicle_data/charges.json
  tests/fixtures/kamereon/vehicle_data/cockpit.json
  tests/fixtures/kamereon/vehicle_data/hvac-status.json
  tests/fixtures/kamereon/vehicle_error/invalid_date.json
  tests/fixtures/kamereon/vehicle_error/invalid_upstream.json
  tests/fixtures/kamereon/vehicle_error/not_supported.json
  tests/fixtures/kamereon/vehicle_error/quota_limit.json
  tests/fixtures/kamereon/vehicles/zoe.1.json
  tests/model/test_kamereon.py
Labels: enhancement

#32 Stubs for Gigya client
  src/renault_api/gigya.py
  src/renault_api/model/gigya.py
  tests/const.py
  tests/test_gigya.py
Labels: enhancement

#41 Ignore mypy missing imports for aioresponses
  mypy.ini
  tests/test_api_keys.py
  tests/test_gigya.py
Labels: CI

#42 Add pyjwt dependency
  poetry.lock
  pyproject.toml
Labels: dependencies

#44 Update handling of JWT tokens
  src/renault_api/gigya.py
  src/renault_api/model/gigya.py
  tests/__init__.py
  tests/model/test_credential.py
  tests/test_gigya.py
Labels: enhancement

#47 Adding Captur 2 with Easylink
  tests/fixtures/kamereon/vehicle_data/cockpit_captur_ii.json
  tests/fixtures/kamereon/vehicles/captur2.json
Labels: CI

#49 Add fixtures from oncleben31
  tests/fixtures/kamereon/error/access_denied.json
  tests/fixtures/kamereon/vehicles/zoe1_without_nav.json
Labels: CI

#50 Add CredentialStore
  src/renault_api/credential_store.py
  src/renault_api/kamereon.py
  tests/__init__.py
  tests/test_credential_store.py
Labels: enhancement

#33 Implement RenaultClient/RenaultAccount
  src/renault_api/exceptions.py
  src/renault_api/model/kamereon.py
  src/renault_api/renault_account.py
  src/renault_api/renault_client.py
  src/renault_api/renault_vehicle.py
  tests/__init__.py
  tests/test_renault_account.py
  tests/test_renault_client.py
Labels: enhancement

#63 Add CI for develop branch
  .github/workflows/develop.yml
Labels: CI

#59 Add Renault vehicle functionnality
  src/renault_api/model/kamereon.py
  src/renault_api/renault_vehicle.py
  tests/fixtures/kamereon/vehicle_data/charge-mode.json
  tests/fixtures/kamereon/vehicle_data/charging-settings.json
  tests/fixtures/kamereon/vehicle_data/cockpit.captur_ii.json
  tests/fixtures/kamereon/vehicle_data/cockpit.zoe.json
  tests/fixtures/kamereon/vehicle_data/hvac-history.json
  tests/fixtures/kamereon/vehicle_data/hvac-sessions.json
  tests/fixtures/kamereon/vehicle_data/location.json
  tests/fixtures/kamereon/vehicle_data/lock-status.json
  tests/fixtures/kamereon/vehicle_data/notification-settings.json
  tests/model/test_kamereon.py
  tests/model/test_kamereon_client.py
  tests/model/test_kamereon_error.py
  tests/model/test_kamereon_vehicle_data.py
  tests/model/test_kamereon_vehicles.py
  tests/test_kamereon_data.py
  tests/test_renault_vehicle.py
Labels: enhancement
