Repository hacf-fr/renault-api, pull requests merged in 2020-12, with the labels that each got.

#77 Add tabulate dependency
  poetry.lock
  pyproject.toml
Labels: dependencies

#81 Update release template
  .github/release-drafter.yml
Labels: ci, documentation

#83 Improve exception handling in RenaultSession
  src/renault_api/exceptions.py
  src/renault_api/renault_session.py
  tests/test_renault_session.py
Labels: python

#84 Add ability to update schedules
  src/renault_api/kamereon/helpers.py
  src/renault_api/kamereon/models.py
  tests/kamereon/test_kamereon_vehicle_data.py
  tests/kamereon/test_kamereon_vehicle_schedule.py
Labels: enhancement

#87 Fix set_charge_mode on RenaultVehicle
  src/renault_api/renault_vehicle.py
  tests/test_renault_vehicle.py
Labels: bug

#82 Add dependencies for CLI
  noxfile.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#92 Bump next to v0.0.3
  pyproject.toml
Labels: python

#88 Add charge control to CLI
  src/renault_api/cli/__main__.py
  src/renault_api/cli/helpers.py
  src/renault_api/cli/renault_vehicle.py
  src/renault_api/cli/renault_vehicle_charge.py
  src/renault_api/kamereon/helpers.py
  src/renault_api/kamereon/models.py
  src/renault_api/renault_vehicle.py
  tests/cli/__init__.py
  tests/cli/test_vehicle.py
  tests/cli/test_vehicle_charge.py
  tests/conftest.py
  tests/fixtures.py
  tests/fixtures/kamereon/vehicle_action/charge-schedule.schedules.json
  tests/fixtures/kamereon/vehicle_data/charge-history.day.json
  tests/fixtures/kamereon/vehicle_data/charge-history.month.json
  tests/test_renault_vehicle.py
Labels: enhancement, fixtures

#97 Refactor fixture injection
  tests/__init__.py
  tests/cli/__init__.py
  tests/cli/test_account.py
  tests/cli/test_client.py
  tests/cli/test_session.py
  tests/cli/test_vehicle.py
  tests/cli/test_vehicle_charge.py
  tests/conftest.py
  tests/fixtures.py
  tests/fixtures/gigya/error/get_jwt.403005.json
  tests/fixtures/gigya/error/get_jwt.403013.json
  tests/fixtures/gigya/error/login.403042.json
  tests/gigya/test_gigya.py
  tests/gigya/test_gigya_error.py
  tests/gigya/test_gigya_models.py
  tests/kamereon/test_kamereon.py
  tests/kamereon/test_kamereon_error.py
  tests/kamereon/test_kamereon_person.py
  tests/kamereon/test_kamereon_vehicle_action.py
  tests/kamereon/test_kamereon_vehicle_data.py
  tests/kamereon/test_kamereon_vehicle_schedule.py
  tests/kamereon/test_kamereon_vehicles.py
  tests/test_api_keys.py
  tests/test_credential.py
  tests/test_credential_store.py
  tests/test_renault_account.py
  tests/test_renault_client.py
  tests/test_renault_session.py
  tests/test_renault_vehicle.py
Labels: testing

#98 Update enums to match MyRenault app
  src/renault_api/cli/renault_vehicle_charge.py
  src/renault_api/kamereon/enums.py
  src/renault_api/kamereon/models.py
  src/renault_api/renault_vehicle.py
  tests/kamereon/test_kamereon_vehicle_data.py
  tests/test_renault_vehicle.py
Labels: breaking

#99 Fix CLI charge-settings schedule-id identification
  .gitignore
  src/renault_api/cli/__main__.py
  src/renault_api/cli/renault_vehicle_charge.py
  tests/cli/test_vehicle_charge.py
  tests/fixtures/kamereon/vehicle_data/charging-settings.json
  tests/kamereon/test_kamereon_vehicle_data.py
  tests/kamereon/test_kamereon_vehicle_schedule.py
Labels: bug

#94 Add HVAC-schedule API-methods.
  src/renault_api/kamereon/__init__.py
  src/renault_api/kamereon/models.py
  src/renault_api/kamereon/schemas.py
  src/renault_api/renault_vehicle.py
  tests/fixtures.py
  tests/fixtures/kamereon/vehicle_action/hvac-schedule.schedules.json
  tests/fixtures/kamereon/vehicle_data/hvac-settings.json
  tests/kamereon/test_kamereon_vehicle_action.py
  tests/kamereon/test_kamereon_vehicle_data.py
  tests/kamereon/test_kamereon_vehicle_schedule.py
  tests/test_renault_vehicle.py
Labels: enhancement, fixtures

#100 Auto-create CLI log folder
  src/renault_api/cli/__main__.py
  tests/cli/test_client.py
  tests/cli/test_main.py
Labels: enhancement

#71 Update documentation
  CONTRIBUTING.rst
  README.rst
  tests/fixtures/kamereon/Contributions.rst
Labels: documentation

#105 Allow unsetting a charge-schedule
  src/renault_api/cli/__main__.py
  src/renault_api/cli/renault_vehicle_charge.py
  src/renault_api/kamereon/models.py
  tests/cli/test_vehicle_charge.py
  tests/fixtures/kamereon/vehicle_action/charge-schedule.schedules.json
  tests/kamereon/test_kamereon_vehicle_action.py
Labels: enhancement

#107 Add HVAC control to CLI
  src/renault_api/cli/__main__.py
  src/renault_api/cli/charge/__init__.py
  src/renault_api/cli/charge/commands.py
  src/renault_api/cli/charge/control.py
  src/renault_api/cli/charge/history.py
  src/renault_api/cli/charge/schedule.py
  src/renault_api/cli/hvac/__init__.py
  src/renault_api/cli/hvac/commands.py
  src/renault_api/cli/hvac/control.py
  src/renault_api/cli/hvac/history.py
  src/renault_api/cli/renault_vehicle_charge.py
  tests/cli/test_vehicle_charge.py
  tests/cli/test_vehicle_hvac.py
Labels: enhancement

#122 Update README
  README.rst
Labels: documentation

#123 Fix coverage badge
  README.rst
Labels: documentation
