Repository hacf-fr/renault-api, pull requests merged in 2021-01, with the labels that each got.

#126 add twingo_ze fixtures file
  tests/fixtures/kamereon/vehicles/twingo_ze.json
Labels: fixtures

#127 Security update to py 1.10.0
  poetry.lock
Labels: dependencies

#137 Update vehicle samples
  CONTRIBUTING.rst
  src/renault_api/kamereon/models.py
  tests/fixtures/kamereon/vehicles/captur_ii.1.json
  tests/fixtures/kamereon/vehicles/twingo_ze.json
  tests/fixtures/kamereon/vehicles/zoe_40.1.json
  tests/fixtures/kamereon/vehicles/zoe_50.1.json
  tests/kamereon/test_kamereon_vehicles.py
Labels: fixtures

#143 Rename VehicleDetails models
  src/renault_api/kamereon/models.py
  src/renault_api/renault_vehicle.py
Labels: breaking

#142 Add ability to get details for a single vehicle
  src/renault_api/cli/__main__.py
  src/renault_api/cli/renault_vehicle.py
  src/renault_api/kamereon/__init__.py
  src/renault_api/kamereon/models.py
  src/renault_api/kamereon/schemas.py
  src/renault_api/renault_session.py
  src/renault_api/renault_vehicle.py
  tests/cli/test_vehicle.py
  tests/fixtures.py
  tests/test_renault_vehicle.py
Labels: enhancement

#139 Add checks for endpoint support
  src/renault_api/cli/renault_vehicle.py
  src/renault_api/kamereon/models.py
  tests/cli/test_account.py
  tests/cli/test_vehicle.py
  tests/fixtures.py
  tests/fixtures/kamereon/vehicles/twingo_ze.1.json
  tests/kamereon/test_kamereon.py
  tests/kamereon/test_kamereon_vehicles.py
  tests/test_renault_account.py
  tests/test_renault_vehicle.py
Labels: enhancement

#144 Add extra installation for contributing
  CONTRIBUTING.rst
Labels: documentation

#162 Update documentation
  docs/endpoints.rst
  docs/endpoints/vehicle_action.charge-mode.rst
  docs/endpoints/vehicle_action.charge-schedule.rst
  docs/endpoints/vehicle_action.charging-start.rst
  docs/endpoints/vehicle_action.hvac-schedule.rst
  docs/endpoints/vehicle_action.hvac-start.rst
  docs/endpoints/vehicle_data.battery-status.rst
  docs/endpoints/vehicle_data.charge-history.rst
  docs/endpoints/vehicle_data.charge-mode.rst
  docs/endpoints/vehicle_data.charges.rst
  docs/endpoints/vehicle_data.charging-settings.rst
  docs/endpoints/vehicle_data.cockpit.rst
  docs/endpoints/vehicle_data.hvac-history.rst
  docs/endpoints/vehicle_data.hvac-sessions.rst
  docs/endpoints/vehicle_data.hvac-settings.rst
  docs/endpoints/vehicle_data.hvac-status.rst
  docs/endpoints/vehicle_data.location.rst
  docs/endpoints/vehicle_data.lock-status.rst
  docs/endpoints/vehicle_data.notification-settings.rst
  docs/index.rst
  docs/reference.rst
  docs/reference/gigya.rst
  docs/reference/kamereon.rst
  docs/reference/renault_api.rst
  docs/usage.rst
  src/renault_api/kamereon/__init__.py
Labels: documentation

#158 Add raw HTTP GET/POST methods to CLI
  src/renault_api/cli/__main__.py
  src/renault_api/cli/renault_client.py
  src/renault_api/gigya/__init__.py
  src/renault_api/kamereon/__init__.py
  src/renault_api/renault_session.py
  tests/cli/test_vehicle.py
Labels: enhancement

#165 Add charging-settings fixture
  src/renault_api/cli/charge/schedule.py
  src/renault_api/kamereon/helpers.py
  src/renault_api/kamereon/models.py
  tests/cli/test_vehicle.py
  tests/cli/test_vehicle_charge.py
  tests/fixtures.py
  tests/fixtures/kamereon/vehicle_data/charging-settings.multi.json
  tests/fixtures/kamereon/vehicle_data/charging-settings.single.json
  tests/kamereon/test_kamereon_vehicle_action.py
  tests/kamereon/test_kamereon_vehicle_data.py
  tests/test_renault_vehicle.py
Labels: fixtures

#166 Update hvac-start endpoint documentation
  docs/endpoints/vehicle_action.hvac-start.rst
Labels: documentation

#172 Add support for `activated` flag in `update_schedule`
  src/renault_api/kamereon/helpers.py
  tests/kamereon/test_kamereon_vehicle_action.py
Labels: enhancement
