Repository hacf-fr/renault-api, pull requests merged in 2022-01, with the labels that each got.

#460 Add Dacia Spring Fixtures & Make minor changes on fixtures
  docs/endpoints/vehicle_data.charging-settings.rst
  docs/endpoints/vehicle_data.hvac-status.rst
  docs/endpoints/vehicle_data.location.rst
  src/renault_api/kamereon/models.py
  tests/fixtures.py
  tests/fixtures/kamereon/vehicle_data/cockpit.spring.json
  tests/fixtures/kamereon/vehicle_data/hvac-status.1.json
  tests/fixtures/kamereon/vehicle_data/hvac-status.2.json
  tests/fixtures/kamereon/vehicle_data/location.1.json
  tests/fixtures/kamereon/vehicle_data/location.2.json
  tests/fixtures/kamereon/vehicles/spring.1.json
  tests/kamereon/test_kamereon_vehicle_data.py
  tests/kamereon/test_kamereon_vehicles.py
Labels: documentation, fixtures

#475 Add Zoe50 fixtures and update documentation
  docs/endpoints/vehicle_data.cockpit.rst
  docs/endpoints/vehicle_data.hvac-status.rst
  tests/fixtures.py
  tests/fixtures/kamereon/vehicle_data/cockpit.zoe_50.json
  tests/fixtures/kamereon/vehicle_data/hvac-status.spring.json
  tests/fixtures/kamereon/vehicle_data/hvac-status.zoe.json
  tests/fixtures/kamereon/vehicle_data/hvac-status.zoe_50.json
Labels: documentation, fixtures

#452 Fix unavailable hvac-status on Zoe50
  src/renault_api/kamereon/models.py
  tests/cli/test_vehicle.py
  tests/fixtures.py
  tests/kamereon/test_kamereon_vehicles.py
  tests/test_renault_vehicle.py
Labels: bug, python

#476 Move details fixtures
  tests/cli/test_account.py
  tests/cli/test_vehicle.py
  tests/fixtures.py
  tests/fixtures/kamereon/vehicle_details/captur_ii.1.json
  tests/fixtures/kamereon/vehicle_details/captur_ii.2.json
  tests/fixtures/kamereon/vehicle_details/duster.1.json
  tests/fixtures/kamereon/vehicle_details/spring.1.json
  tests/fixtures/kamereon/vehicle_details/twingo_ze.1.json
  tests/fixtures/kamereon/vehicle_details/zoe_40.1.json
  tests/fixtures/kamereon/vehicle_details/zoe_40.2.json
  tests/fixtures/kamereon/vehicle_details/zoe_50.1.json
  tests/kamereon/test_kamereon_vehicle_details.py
Labels: fixtures

#477 Ignore N815 error on a global basis
  .flake8
  src/renault_api/gigya/models.py
  src/renault_api/kamereon/models.py
Labels: ci

#478 Adjust rule for hiding PII data
  tests/const.py
  tests/fixtures.py
  tests/kamereon/test_kamereon_vehicle_details.py
Labels: ci

#479 Add car gateway fixtures
  src/renault_api/kamereon/models.py
  src/renault_api/kamereon/schemas.py
  tests/fixtures/kamereon/vehicle_gateway/duster.1.json
  tests/fixtures/kamereon/vehicle_gateway/twingo_ze.1.json
  tests/fixtures/kamereon/vehicle_gateway/zoe_40.1.json
  tests/fixtures/kamereon/vehicle_gateway/zoe_50.1.json
  tests/kamereon/test_kamereon_vehicle_gateway.py
Labels: fixtures

#481 Enable hvac-status on TwingoZE
  src/renault_api/kamereon/models.py
  tests/cli/test_vehicle.py
  tests/fixtures.py
  tests/kamereon/test_kamereon_vehicle_details.py
Labels: bug

#480 Add car adapter endpoint
  src/renault_api/kamereon/__init__.py
  src/renault_api/kamereon/models.py
  src/renault_api/renault_session.py
  src/renault_api/renault_vehicle.py
  tests/fixtures.py
  tests/kamereon/__init__.py
  tests/kamereon/test_kamereon_vehicle_details.py
  tests/kamereon/test_kamereon_vehicle_gateway.py
  tests/test_renault_vehicle.py
Labels: enhancement, python

#482 Simplify access to car adapter endpoint
  src/renault_api/kamereon/__init__.py
  src/renault_api/renault_session.py
  src/renault_api/renault_vehicle.py
  tests/fixtures.py
Labels: python

#489 Add gateway fixture for Dacia Spring
  tests/fixtures/kamereon/vehicle_gateway/spring.1.json
Labels: fixtures
