Repository hacf-fr/renault-api, pull requests merged in 2022-02, with the labels that each got.

#495 Add vehicle details fixtures
  tests/fixtures/kamereon/vehicle_details/zoe_40.1.json
  tests/kamereon/test_kamereon_vehicle_details.py
Labels: fixtures

#496 Fix check for energy type in CLI
  src/renault_api/kamereon/models.py
  tests/fixtures.py
  tests/kamereon/test_kamereon_vehicle_details.py
Labels: bug

#497 Add recommendations for vscode extensions
  .vscode/extensions.json
Labels: ci

#498 Add vscode formatting provider
  .vscode/settings.json
Labels: ci

#499 Add vscode tasks
  .vscode/tasks.json
Labels: ci

#500 Add charge stop functionnality
  src/renault_api/cli/charge/commands.py
  src/renault_api/cli/charge/control.py
  src/renault_api/renault_vehicle.py
  tests/cli/test_vehicle_charge.py
  tests/fixtures/kamereon/vehicle_action/charging-start.stop.json
Labels: enhancement

#503 Deprecate methods for required contracts
  src/renault_api/kamereon/__init__.py
  src/renault_api/renault_vehicle.py
Labels: breaking

#504 Deprecate short endpoints for vehicle actions
  src/renault_api/kamereon/__init__.py
  src/renault_api/renault_session.py
  src/renault_api/renault_vehicle.py
Labels: breaking

#506 Implement lock-status
  docs/endpoints/vehicle_data.lock-status.rst
  src/renault_api/kamereon/models.py
  src/renault_api/kamereon/schemas.py
  tests/fixtures.py
  tests/fixtures/kamereon/vehicle_data/lock-status.1.json
  tests/fixtures/kamereon/vehicle_data/lock-status.2.json
  tests/fixtures/kamereon/vehicle_data/lock-status.json
  tests/kamereon/test_kamereon_vehicle_data.py
Labels: documentation, enhancement, fixtures

#502 Add support for Dacia Spring charge control
  docs/endpoints.rst
  docs/endpoints/vehicle_kcm_actions.charge-pause-resume.rst
  src/renault_api/kamereon/__init__.py
  src/renault_api/kamereon/models.py
  src/renault_api/renault_session.py
  src/renault_api/renault_vehicle.py
  tests/cli/test_vehicle_charge.py
  tests/fixtures.py
  tests/fixtures/kamereon/vehicle_kcm_action/charge-pause-resume.pause.json
  tests/fixtures/kamereon/vehicle_kcm_action/charge-pause-resume.resume.json
  tests/kamereon/test_kamereon_vehicle_details.py
  tests/kamereon/test_kamereon_vehicle_gateway.py
  tests/kamereon/test_kamereon_vehicles.py
  tests/test_renault_vehicle.py
Labels: documentation, enhancement, fixtures

#508 Add lock status to CLI
  src/renault_api/cli/renault_vehicle.py
  src/renault_api/kamereon/models.py
  tests/cli/test_vehicle.py
  tests/fixtures.py
Labels: enhancement

#520 Fix parsing issue for lists returned by the Renault servers
  src/renault_api/kamereon/__init__.py
  tests/cli/test_vehicle.py
  tests/fixtures.py
  tests/fixtures/kamereon/person/notifications.1.json
Labels: bug, fixtures

#522 Add support for res-state endpoint
  docs/endpoints.rst
  docs/endpoints/vehicle_data.res-state.rst
  src/renault_api/cli/renault_vehicle.py
  src/renault_api/kamereon/__init__.py
  src/renault_api/kamereon/models.py
  src/renault_api/kamereon/schemas.py
  src/renault_api/renault_vehicle.py
  tests/cli/test_vehicle.py
  tests/fixtures.py
  tests/fixtures/kamereon/vehicle_data/res-state.1.json
  tests/fixtures/kamereon/vehicle_data/res-state.2.json
  tests/kamereon/test_kamereon_vehicle_data.py
Labels: documentation, enhancement, fixtures
