Repository hacf-fr/renault-api, pull requests merged in 2022-03, with the labels that each got.

#537 Cleanup has_contract in CLI
  src/renault_api/cli/renault_vehicle.py
Labels: python

#538 Add explicit support for Python 3.10
  .github/workflows/release.yml
  .github/workflows/tests.yml
  noxfile.py
  pyproject.toml
Labels: enhancement, python, ci

#539 Adding --json support for status command
  src/renault_api/cli/renault_vehicle.py
  tests/cli/test_vehicle.py
Labels: enhancement, python

#552 Update default Kamereon API key
  src/renault_api/const.py
Labels: bug

#569 Check for invalid JSON returned by the API
  src/renault_api/kamereon/__init__.py
  tests/fixtures.py
  tests/fixtures/kamereon/error/bad_gateway.html
  tests/kamereon/test_kamereon.py
Labels: bug, fixtures

#579 Loosen all dependencies
  pyproject.toml
Labels: dependencies
