Repository hacf-fr/renault-api, pull requests merged in 2023-01, with the labels that each got.

#776 Bump gitpython to 3.1.30 and certifi to 2022.12.07
  poetry.lock
  pyproject.toml
Labels: dependencies, python

#778 Move EXPECTED_SPECS to json fixture
  tests/fixtures/kamereon/expected_specs.json
  tests/fixtures/kamereon/vehicles/captur_ii.1.json
  tests/fixtures/kamereon/vehicles/zoe_40.2.json
  tests/kamereon/test_kamereon_vehicle_details.py
  tests/kamereon/test_kamereon_vehicles.py
Labels: ci

#722 Add support for vehicle picture
  src/renault_api/kamereon/enums.py
  src/renault_api/kamereon/models.py
  tests/fixtures/kamereon/expected_specs.json
  tests/kamereon/test_kamereon_vehicle_details.py
  tests/kamereon/test_kamereon_vehicle_gateway.py
  tests/kamereon/test_kamereon_vehicles.py
Labels: enhancement
