Repository hacf-fr/renault-api, pull requests merged in 2024-08, with the labels that each got.

#1304 Added unconfirmed plug state 3
  src/renault_api/kamereon/enums.py
Labels: bug

#1306 Rename charge_schedule helpers
  src/renault_api/kamereon/helpers.py
  src/renault_api/kamereon/models.py
Labels: breaking

#1301 Add helper methods to update HVAC schedules
  src/renault_api/kamereon/helpers.py
  src/renault_api/kamereon/models.py
  tests/kamereon/test_kamereon_vehicle_action.py
Labels: enhancement
