Repository hacf-fr/renault-api, pull requests merged in 2024-04, with the labels that each got.

#1137 Bump cryptography from 42.0.4 to 42.0.5
  poetry.lock
  pyproject.toml
Labels: dependencies

#1136 Replace bandit/flake8/isort with ruff
  .flake8
  .pre-commit-config.yaml
  noxfile.py
  poetry.lock
  pyproject.toml
Labels: ci

#1138 Unignore Ruff rules
  bandit.yml
  pyproject.toml
  src/renault_api/cli/charge/schedule.py
  src/renault_api/cli/renault_settings.py
  src/renault_api/gigya/__init__.py
  src/renault_api/renault_vehicle.py
  tests/conftest.py
  tests/gigya/test_gigya.py
  tests/kamereon/test_kamereon.py
  tests/kamereon/test_kamereon_vehicle_action.py
  tests/kamereon/test_kamereon_vehicle_contract.py
  tests/ruff.toml
  tests/test_api_keys.py
  tests/test_renault_account.py
  tests/test_renault_client.py
  tests/test_renault_session.py
  tests/test_renault_vehicle.py
Labels: ci

#1139 Replace black with ruff
  .pre-commit-config.yaml
  noxfile.py
  pyproject.toml
  src/renault_api/kamereon/__init__.py
  src/renault_api/kamereon/helpers.py
Labels: ci

#1141 Add pyupgrade ruff rules
  pyproject.toml
  src/renault_api/kamereon/helpers.py
  src/renault_api/renault_vehicle.py
  tests/fixtures.py
  tests/test_api_keys.py
Labels: ci

#1142 Cleanup black settings
  README.rst
  poetry.lock
Labels: ci

#1146 Add ruff badge
  README.rst
Labels: documentation

#1145 fix: Go back to Version 1 for Cockpit Endpoint
  src/renault_api/kamereon/__init__.py
  tests/fixtures.py
Labels: bug
