Repository hacf-fr/renault-api, pull requests merged in 2025-03, with the labels that each got.

#1483 Add examples for raw http calls
  README.rst
Labels: documentation

#1508 Fix CI warnings
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  src/renault_api/kamereon/__init__.py
  tests/cli/test_vehicle.py
  tests/fixtures.py
Labels: ci

#1507 Added V2L ChargeStatus to Kamereon enums
  src/renault_api/kamereon/enums.py
Labels: bug, enhancement

#1514 Add fixtures for Renault 5 E-Tech (52kWh)
  tests/fixtures/kamereon/vehicle_data/battery-status.renault_5.json
  tests/fixtures/kamereon/vehicle_data/cockpit.renault_5.json
  tests/fixtures/kamereon/vehicle_data/hvac-status.renault_5.json
  tests/fixtures/kamereon/vehicles/renault_5.1.json
Labels: fixtures
