Repository hacf-fr/renault-api, pull requests merged in 2025-05, with the labels that each got.

#1569 Bump cryptography to 44.0.0
  poetry.lock
  pyproject.toml
Labels: dependencies

#1570 Align get_charging_status with get_plug_status
  src/renault_api/kamereon/models.py
Labels: python

#1567 Add Twingo III and Zoe 2 to the known vehicle endpoint lists
  src/renault_api/kamereon/models.py
  tests/__snapshots__/test_renault_vehicle.ambr
  tests/cli/__snapshots__/test_vehicle.ambr
  tests/test_renault_vehicle.py
Labels: ci
