Repository hacf-fr/renault-api, pull requests merged in 2025-06, with the labels that each got.

#1598 Migrate charge start/stop to EndpointDefinition
  src/renault_api/kamereon/models.py
  src/renault_api/renault_vehicle.py
  tests/__snapshots__/test_renault_vehicle.ambr
Labels: python

#1601 Deprecate controls_action_via_kcm
  src/renault_api/kamereon/models.py
Labels: breaking

#1604 Add get_charge_schedule to RenaultVehicle
  src/renault_api/cli/charge/schedule.py
  src/renault_api/kamereon/models.py
  src/renault_api/renault_vehicle.py
  tests/__snapshots__/test_renault_vehicle.ambr
  tests/test_renault_vehicle.py
Labels: enhancement

#1607 Remove deprecated get/has required contracts
  src/renault_api/kamereon/__init__.py
  tests/kamereon/test_kamereon_vehicle_contract.py
Labels: breaking

#1608 Add start-horn and start-lights methods to vehicle
  src/renault_api/kamereon/models.py
  src/renault_api/renault_vehicle.py
  tests/__snapshots__/test_renault_vehicle.ambr
  tests/fixtures.py
  tests/fixtures/kamereon/vehicle_action/horn-lights.horn.json
  tests/fixtures/kamereon/vehicle_action/horn-lights.lights.json
  tests/test_renault_vehicle.py
Labels: enhancement

#1613 Add vehicle method to get soc limits
  src/renault_api/kamereon/models.py
  src/renault_api/kamereon/schemas.py
  src/renault_api/renault_vehicle.py
  tests/__snapshots__/test_renault_vehicle.ambr
  tests/fixtures.py
  tests/test_renault_vehicle.py
Labels: enhancement
