Repository hacf-fr/renault-api, pull requests merged in 2025-01, with the labels that each got.

#1405 Add vehicle code XCB1SE for SCENIC E-TECH
  src/renault_api/kamereon/models.py
Labels: enhancement

#1411 Add new endpoint for tyre pressure
  src/renault_api/cli/renault_vehicle.py
  src/renault_api/kamereon/__init__.py
  src/renault_api/kamereon/models.py
  src/renault_api/kamereon/schemas.py
  src/renault_api/renault_vehicle.py
  tests/cli/test_vehicle.py
  tests/fixtures.py
  tests/fixtures/kamereon/vehicle_data/tyre-pressure.json
  tests/kamereon/test_kamereon_vehicle_data.py
  tests/test_renault_vehicle.py
Labels: enhancement, fixtures

#1419 Drop support for Python 3.8
  .github/workflows/tests.yml
  CONTRIBUTING.rst
  README.rst
  noxfile.py
  pyproject.toml
Labels: breaking
